/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pkg3itb2_patnactka;

import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.JButton;
import javax.swing.JOptionPane;

/**
 *
 * @author usd07
 */
public class Okno extends javax.swing.JFrame {

    private logikahtHry logika;
    private JButton[][] tlacitka=new JButton[4][4]; //inicialiyovane pole, musime ale inicializovat jednotliva tlacitka
    
    public Okno(logikahtHry logika) {
        initComponents();
        this.logika=logika;
        PridejTlacitka();
        NaplnTlacitkaHodnotamaZPole();
        PridejUdalostiTlacitek();
    }
    
    private void PridejTlacitka(){
        for (int i = 0; i < tlacitka.length; i++) {
            for (int j = 0; j < tlacitka[0].length; j++) {
                tlacitka[i][j]=new JButton();
                tlacitka[i][j].setSize(50,50);
                tlacitka[i][j].setVisible(true);
                this.add(tlacitka[i][j]);
                tlacitka[i][j].setLocation(j*50, i*50);
                tlacitka[i][j].setName(i+","+j); //ulozime si souradnice tlacitka v poli
            }
        }
    }
    
    private void PridejUdalostiTlacitek(){
        for (int i = 0; i < tlacitka.length; i++) {
            for (int j = 0; j < tlacitka[0].length; j++) {
                tlacitka[i][j].addMouseListener(new MouseAdapter() {
                    @Override
                    public void mouseClicked(MouseEvent me) {
                        //toto se provede pri stisku tlacitka
                        System.out.println("klik");
                        //musime poslat info o tom na jake tlacitko v poli jsme kliknuli
                        // souradnice si ulozime do vlastnosti Name
                        
                        ////// ziskani tlacitka co vyvolalo udalost
                        JButton pomocneTl=(JButton)(me.getSource()); //objekt ktery sme ziskali z me.getSource() jsem pretzpovali na JButton
                        /// ziskani souradnic z Name tlacitka
                        String[] souradniceVeStringu=pomocneTl.getName().split(","); //prvni prvek v poli odpovida souradnici i a druhy prvek odpovida souradnici j
                        
                        logika.PresunCislo(Integer.parseInt(souradniceVeStringu[0]), Integer.parseInt(souradniceVeStringu[1]));
                        if(logika.Vyhodnot()){
                            JOptionPane.showMessageDialog(null,"Vyhrál jsi!");  
                        }
                        NaplnTlacitkaHodnotamaZPole();
                        
                        super.mouseClicked(me); //To change body of generated methods, choose Tools | Templates.
                    }
                    
                
                });
            
            }
        }
    }
    
    private void NaplnTlacitkaHodnotamaZPole(){
        for (int i = 0; i < tlacitka.length; i++) {
            for (int j = 0; j < tlacitka[0].length; j++) {
                tlacitka[i][j].setText(logika.getHodnotyPole()[i][j]+"");
                if(logika.getHodnotyPole()[i][j]==0){
                    //prazdne policko
                    tlacitka[i][j].setText("");
                }
            }
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 650, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 584, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Okno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Okno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Okno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Okno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               // new Okno().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
